name: Build and Deploy Spring Boot Jar

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Perform Security Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java,depscan"

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports

      - name: Remove target directory
        run: sudo rm -rf target/*

      - name: Maven clean
        run: mvn clean

      - name: Build with Maven
        run: mvn -X package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-carsmovies.jar
          path: target/spring-boot-carsmovies.jar

      - name: List target directory contents
        run: ls -l target